server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/devboard
    username: devboard
    password: devboard
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
